stages:
  - lint
  - build
  - deploy

eslint:
  image: node:latest
  stage: lint
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js .
  tags:
    - spot


build:
  image: node:latest
  stage: build
  script:
    - npm build
  tags:
    - spot

staging:
  type: deploy
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=midgard-bff --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master

cache:
  paths:
    - node_modules/
